from random import randint
quotes = [
"A long time ago in a galaxy far, far away…",
"Help me, Obi-Wan Kenobi. You’re my only hope.",
"It’s not my fault.",
"The garbage’ll do!",
"I’ll never turn to the dark side. You’ve failed, your highness. I am a Jedi, like my father before me.",
"May the Force be with you.",
"I am altering the deal, pray I do not alter it further.",
"Your weapon… you will not need it.",
"Now, young Skywalker, you will die.",
"Your focus determines your reality.",
"Let the past die. Kill it if you have to.",
"Everything you’ve heard about me is true.",
"If we can make it to the ground, we’ll take the next chance. And the next. On and on until we win… or the chances are spent.",
"I find your lack of faith disturbing.",
"What an incredible smell you’ve discovered.",
"I’m one with the Force. The Force is with me.",
"Do. Or do not. There is no try.",
"I’ve got a bad feeling about this.",
"So who talks first, you talk first, I talk first?",
"I’m just a simple man trying to make my way in the universe.",
"You can’t stop the change, any more than you can stop the suns from setting.",
"It’s a trap!",
"So this is how liberty dies…with thunderous applause.",
"I wouldn’t be nice to you. It doesn’t pay much.",
"In my experience there is no such thing as luck.",
"Save the rebellion. Save the dream",
"Somebody has to save our skins.",
"I’m Luke Skywalker and I’m here to rescue you! ",
"Every time I walked away from something I wanted to forget, I told myself it was for a cause that I believed in. A cause that was worth it. Without that, we’re lost.",
"No. I am your father.",
"I’m rather embarrassed, General Solo, but it appears that you are to be the main course at a banquet in my honor. - C-3PO",
"I love that Wookie! – Maz Kanata",
"Remember, Your focus determines your reality.  — Qui-Gon Jinn",
"I fear nothing. For all is as the Force wills it.  – Chirrut Imwe",
"An elegant weapon for a more civilized age.  – Obi-Wan Kenobi",
"No! I don’t think he likes you at all. No, I don’t like you either.  – C-3PO",
"Stay on target.  – Gold Five",
"Always in motion is the future. - Yoda",
"The ability to speak does not make you intelligent, now get out of here.  – Qui-Gon Jinn",
"Would somebody get this big walking carpet out of my way?  – Leia Organa",
"Jyn, I’ll be there for you. Cassian said I had to.  — K-2SO",
"Use the Force, Luke.",
"What if I told you that the Republic was now under the control of a Dark Lord of the Sith?  — Count Dooku",
"In time, the suffering of your people will persuade you to see our point of view.  — Nute Gunray"
"Laugh it up, fuzzball!  – Han Solo",
" This is a new day, a new beginning.  – Ahsoka Tano",
"When nine hundred years old you reach, look as good you will not.  – Yoda",
"The dark side of the Force is a pathway to many abilities some consider to be unnatural.  — Chancellor Palpatine",
"Attachment is forbidden. Possession is forbidden. Compassion, which I would define as unconditional love, is essential to a Jedi’s life. So you might say, that we are encouraged to love.  — Anakin"
"Power! Unlimited power!"
]
randomq = quotes[randint(0, len(quotes)-1)]
print(randomq)
